"""empty message

Revision ID: 2bbde6c4ca4e
Revises: ce8a239249e6
Create Date: 2025-01-10 19:07:12.326915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbde6c4ca4e'
down_revision = 'ce8a239249e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('FollId',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['followers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('forum_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'forums', ['forum_id'], ['id'])

    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('follower_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('unique_followers', type_='unique')
        batch_op.drop_constraint('followers_followers_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['follower_id'], ['id'])
        batch_op.drop_column('followers_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('followers_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('followers_followers_id_fkey', 'users', ['followers_id'], ['id'])
        batch_op.create_unique_constraint('unique_followers', ['followers_id', 'followed_id'])
        batch_op.drop_column('follower_id')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('forum_id')

    op.drop_table('FollId')
    # ### end Alembic commands ###
