"""empty message

Revision ID: 633bc03a0d1a
Revises: d57f71c86b4b
Create Date: 2024-12-27 15:07:04.677719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '633bc03a0d1a'
down_revision = 'd57f71c86b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forum')
    # ### end Alembic commands ###
