"""empty message

Revision ID: d57f71c86b4b
Revises: 2f42fb0467f1
Create Date: 2024-12-26 22:45:14.130067

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd57f71c86b4b'
down_revision = '2f42fb0467f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.drop_constraint('followers_followed_id_key', type_='unique')
        batch_op.drop_constraint('followers_followers_id_key', type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('followers', schema=None) as batch_op:
        batch_op.create_unique_constraint('followers_followers_id_key', ['followers_id'])
        batch_op.create_unique_constraint('followers_followed_id_key', ['followed_id'])

    # ### end Alembic commands ###
